# Generated by Django 6.0.7 on 2026-07-17 06:37

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_url', models.URLField(max_length=2048)),
                ('canonical_url', models.URLField(blank=True, max_length=2048)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('collecting', 'Collecting'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('collector_schema_version', models.CharField(blank=True, max_length=100)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('risk_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('verdict', models.CharField(blank=True, max_length=50)),
                ('summary', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analysis_jobs',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'created_at'], name='analysis_status_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('risk_score__lte', 100)), name='analysis_risk_score_lte_100')],
            },
        ),
    ]
